typography_spectrum: 0.7113147529307753
content_rating:
  adult: false
color:
  brandColors:
    - '#E8E595'
    - '#D0A825'
    - '#40627C'
    - '#26393D'
    - '#FFFAE4'
  brandStrength: 0.05203864714323836
  lightness: 0.8235387648032428
  saturation: 0.0939502225795269
  rhythmicContrast: 0.30747255987246935
github: true
opengraph:
  type: ''
  appId: ''
layout_spectrum: 0.5494005540385842
author:
  name: Shaine Mata
  url: 'http://www.shainemata.com'
  email: shaine@shainemata.com
name: 'Mission, Texas Guide'
navigation:
  - name: Advertise
    id: 62a7e29a-68bf-4813-9511-ab6337958c30
    type: content
  - name: Contact
    id: f0461174-7e15-4bef-ba42-38ecf644b071
    type: content
  - name: About
    id: 9a2aa503-1ea5-4d24-82c5-986191c78f54
    type: content
  - name: Blog
    url: 'http://blog.missiontexas.net/'
    type: external
  - name: Upcoming Events
    id: 0974496f-6a2c-4383-8db9-dd338fbe0d85
    type: content
  - name: Business Directory
    id: 68ebd1a1-1948-486c-bd75-d7f8b54ac140
    type: content
title: 'Mission, Texas Guide'
description: 'Find it here '
purpose:
  - type: internal
    label: Click Here to Advertise
    item: 62a7e29a-68bf-4813-9511-ab6337958c30
