typography_spectrum: 0.434025622358601
content_rating:
  adult: false
color:
  brandColors:
    - '#020003'
    - '#D37302'
    - '#8E2F03'
    - '#CECCBF'
    - '#648C08'
  brandStrength: 0.9378539630757774
  lightness: 0.7493970519080205
  saturation: 0.9453500186716491
  rhythmicContrast: 0.9013340855671996
github: true
opengraph:
  type: ''
  appId: ''
layout_spectrum: 0.824876752420891
author:
  name: Shaine Mata
  url: 'http://www.shainemata.com'
  email: shaine@shainemata.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b93f3b9a-cefd-4ef0-a12e-1d5657260a98.png
name: 'Mission, Texas Guide'
navigation:
  - name: Events
    id: 0974496f-6a2c-4383-8db9-dd338fbe0d85
    type: content
  - name: Directory
    id: 68ebd1a1-1948-486c-bd75-d7f8b54ac140
    type: content
  - name: History
    id: fc1b2c87-64c0-4e77-a59e-303bde9975c1
    type: content
  - name: Activities
    id: 449bf259-60ee-4e72-9d4a-9ad9288ac175
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4db740d0-84c2-4088-9140-6f09088d28fd.ico
title: 'Mission, Texas Guide'
content: []
description: 'Find out here '
purpose: []
