typography_spectrum: 0.342276620445773
content_rating:
  adult: false
color:
  brandColors:
    - '#E8E595'
    - '#D0A825'
    - '#40627C'
    - '#26393D'
    - '#FFFAE4'
  brandStrength: 0.05203864714323836
  lightness: 0.8235387648032428
  saturation: 0.0939502225795269
  rhythmicContrast: 0.30747255987246935
github: true
opengraph:
  type: ''
  appId: ''
layout_spectrum: 0.7400550576858222
author:
  name: Shaine Mata
  url: 'http://www.shainemata.com'
  email: shaine@shainemata.com
name: 'Mission, Texas Guide'
navigation:
  - name: Advertise
    id: 62a7e29a-68bf-4813-9511-ab6337958c30
    type: content
title: 'Mission, Texas Guide'
description: 'Find it here '
purpose: []
