layout_spectrum: 0.8217545799618715
typography_spectrum: 0.1450782870989994
color:
  brandColors:
    - '#020003'
    - '#D37302'
    - '#8E2F03'
    - '#CECCBF'
    - '#648C08'
  brandStrength: 0.9354374381618593
  lightness: 0.7440771990235304
  saturation: 0.942079271538515
  rhythmicContrast: 0.9082652596203555
content_rating:
  adult: false
github: true
opengraph:
  type: ''
  appId: ''
author:
  name: Shaine Mata
  url: 'http://www.shainemata.com'
  email: shaine@shainemata.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b93f3b9a-cefd-4ef0-a12e-1d5657260a98.png
name: 'Mission, Texas Guide'
navigation:
  - name: Directory
    id: 68ebd1a1-1948-486c-bd75-d7f8b54ac140
    type: content
  - name: History
    id: fc1b2c87-64c0-4e77-a59e-303bde9975c1
    type: content
  - name: Activities
    id: 449bf259-60ee-4e72-9d4a-9ad9288ac175
    type: content
  - name: Blog
    url: 'http://blog.missiontexas.net'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4db740d0-84c2-4088-9140-6f09088d28fd.ico
title: 'Mission, Texas Guide'
content: []
description: 'Find out here '
purpose:
  - type: external
    url: 'http://blog.missiontexas.net'
    label: Blog
