typography_spectrum: 0.7113147529307753
content_rating:
  adult: false
color:
  brandColors:
    - '#E8E595'
    - '#D0A825'
    - '#40627C'
    - '#26393D'
    - '#FFFAE4'
  brandStrength: 0.05203864714323836
  lightness: 0.8235387648032428
  saturation: 0.0939502225795269
  rhythmicContrast: 0.30747255987246935
github: true
opengraph:
  type: ''
  appId: ''
layout_spectrum: 0.5494005540385842
author:
  name: Shaine Mata
  url: 'http://www.shainemata.com'
  email: shaine@shainemata.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b93f3b9a-cefd-4ef0-a12e-1d5657260a98.png
name: 'Mission, Texas Guide'
navigation:
  - name: About
    id: 9a2aa503-1ea5-4d24-82c5-986191c78f54
    type: content
  - name: Blog
    url: 'http://blog.missiontexas.net/'
    type: external
  - name: Upcoming Events
    id: 0974496f-6a2c-4383-8db9-dd338fbe0d85
    type: content
  - name: Business Directory
    id: 68ebd1a1-1948-486c-bd75-d7f8b54ac140
    type: content
  - name: History
    id: fc1b2c87-64c0-4e77-a59e-303bde9975c1
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4db740d0-84c2-4088-9140-6f09088d28fd.ico
title: 'Mission, Texas Guide'
content: []
description: 'Find it here '
purpose:
  - type: internal
    label: Click Here to Advertise
    item: 62a7e29a-68bf-4813-9511-ab6337958c30
